# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - VinculusNotificacao

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_39aeac244fa24991877cf3c294456b4c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4f1bbecfbed14813836e349bd178168a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_39aeac244fa24991877cf3c294456b4c }}/midylena/vinculus_notificacao:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'VinculusNotificacao'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3125d72583e249e9b50a99a8b298a096 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_39aeac244fa24991877cf3c294456b4c }}/midylena/vinculus_notificacao:${{ github.sha }}'